# Generated by Django 2.0.5 on 2018-05-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20180506_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, '最新文章'), (2, '最热文章'), (3, '最近评论'), (4, 'HTML'), (5, '友链')], default=1, verbose_name='展示类型'),
        ),
    ]
