# Generated by Django 2.0.5 on 2018-05-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-id',), 'verbose_name': '  文章', 'verbose_name_plural': '  文章'},
        ),
    ]
