# Generated by Django 2.0.5 on 2018-05-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_is_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html',
            field=models.TextField(default='', help_text='正文仅支持Markdown语法', verbose_name='渲染后的内容'),
        ),
    ]
