FROM python:3.7

# Sane defaults for pip
ENV PIP_NO_CACHE_DIR off
ENV PIP_DISABLE_PIP_VERSION_CHECK on
ENV PYTHONUNBUFFERED 1

## Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./requirements /requirements

## --no-cache-dir
RUN pip install -r /requirements/base.txt -i https://pypi.doubanio.com/simple
RUN pip install -r /requirements/develop.txt -i https://pypi.doubanio.com/simple
RUN pip install -r /requirements/product.txt -i https://pypi.doubanio.com/simple
RUN pip install https://codeload.github.com/sshwsfc/xadmin/zip/django2

COPY ./compose/django/entrypoint.sh /entrypoint.sh
RUN sed -i 's/\r//' /entrypoint.sh
RUN chmod +x /entrypoint.sh

# 去除windows系统换行符
COPY ./compose/django/gunicorn.sh /gunicorn.sh
RUN sed -i 's/\r//' /gunicorn.sh
RUN chmod +x /gunicorn.sh

WORKDIR /webapp

ENTRYPOINT ["/entrypoint.sh"]
